# Generated by Django 4.1.3 on 2022-11-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_phone_alter_profile_user_and_more'),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinput',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_input', to='accounts.profile'),
        ),
    ]
