# Generated by Django 4.1.3 on 2022-11-08 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codelist', '0002_alter_listinput_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinput',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
